trigger:
- main
 
pool:
  vmImage: ubuntu-latest
 
steps:
- task: vercel-deployment-task@1
  inputs:
    vercelProjectId: $(vercelProjectId)
    vercelOrgId: $(vercelOrgId)
    vercelToken: $(VERCEL_TOKEN)
    production: true